### ISSUE TITLE
Próximos passos

### ISSUE THREAD

**Issue by ocefpaf** [LaPoGeoMar/Proj_Pellets_Amarelamento#12]
Até agora fizemos:
- ler as imagens dos pellets em série
- remover o fundo para evitar contaminação da cor*
- identificar a cor dominante
- gerar uma tabela com nome do pellet como index e colunas R, G, B da cor dominante**
- notebooks experimentais com a determinação do amarelamento usando a chave de identificação da Dani***

Próximos passos:

- identificar quais pellets devemos remover seja por serem translúcidos (\*) ou terem cores/formas  que prejudicam sua classificação por grau de amarelamento
- criar uma tabela com o nome do pellet, mesmo usado em \*\* e a identificação da Dani para comparação dos métodos que vamos tentar
- re-fazer o notebook experimental com a chave da Dani usando a cor dominante e criar um critério de classificação, a princípio, pelo brilho do canal Azu (B)

Qualquer coisa pergunta aqui ou podemos marcar uma ligação.

**Comment by jojobozz** [comment]
Oi @ocefpaf, vou escrever sobre cada passo abaixo e as dúvidas que surgiram 

> identificar quais pellets devemos remover seja por serem translúcidos (*) ou terem cores/formas que prejudicam sua classificação por grau de amarelamento

Sobre esse primeiro ponto, dei uma olhada nas imagens e não cheguei a notar nenhuma que não pudesse ser classificada, o que percebi é que algumas delas a "cor dominante" não é a cor da classificação visual, são essas que devemos remover? Um exemplo seria a imagem `Proj_Pellets_Amarelamento/notebooks/temp/check-cl1_p1_psul_deixa5_h0011.png`

> criar uma tabela com o nome do pellet, mesmo usado em ** e a identificação da Dani para comparação dos métodos que vamos tentar

Esta tabela seria o nome do pellet e a classificação visual? Se sim, já está pronta :pray:

> re-fazer o notebook experimental com a chave da Dani usando a cor dominante e criar um critério de classificação, a princípio, pelo brilho do canal Azu (B)

Estou mexendo no notebook experimental para criar um critério de classificação, e agora estou buscando que análise estatística poderia utilizar para validar/encontrar este critério, pelos dados da Dani só o canal do Azul não classificaria, pois os valores de B das classes alto e muitoalto e das classes nulo e baixo apresentam valores semelhantes. Os valores de R quase não variam, mas no G variam, então pensei que poderia ser feita a análise utilizando G e B, pensei em fazer isso através de uma divisão dos valores G/B, efetuei isso na rotina_08_classes_zanetti (que fiz o commit a pouco). 

Desculpe o textão, ainda to um pouco confusa sobre os passos, mas espero que a gente chegue lá!

**Comment by ocefpaf** [comment]
> o que percebi é que algumas delas a "cor dominante" não é a cor da classificação visual, são essas que devemos remover? Um exemplo seria a imagem `Proj_Pellets_Amarelamento/notebooks/temp/check-cl1_p1_psul_deixa5_h0011.png`

Diria que a princípio sim. Conversei com a Ju e talvez esses pellets possam ter descamado, revelando partes "mais novas sob a parte mais velha." Daí, infelizmente, só seria possível incluir esses se a gente clicasse no amarelo mais forte, ou criar uma forma de achar o amarelo mais forte. O primeiro é um retorno ao processo manual e o segundo devemos deixar para trabalhos futuros.

> Esta tabela seria o nome do pellet e a classificação visual? Se sim, já está pronta pray

Show!

> Desculpe o textão, ainda to um pouco confusa sobre os passos, mas espero que a gente chegue lá!

Textão é bom. Vamos devagar e sempre. Vou ver seus notebooks amanhã e te dou um feedback. Uma outra alternativa seria usar uma escala de cinza especial, [a default é](https://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_rgb_to_gray.html) `Y = 0.2125 R + 0.7154 G + 0.0721 B`, que seria aproximadamente 21% Vermelho. 72% Verde, e 7% Azul. Podemos tentar um com menos bias no vermelho e mais no verde e azul para garantir os efeitos deles no brilho. Mas não perde muito tempo nisso... É uma idea meio maluca e talvez a gente não tenha tempo para tentar. Acho que vale mais à pena olhar para os valores de HSV (Hue, Saturation, Value) e/ou usar um critério com if-clauses em ambos verde/azul. Ao do tipo:

```
(if value_Blue >= X_Blue) and (value_Green <= Y_Green) => amarelamento baixo
```

Em alguns casos essa combinação linear pode ficar complexa já que ambos `value_Blue` e `value_Green` podem ficar entre `>=`, `<`, tipo:

```
(if X0_Blue >= value_Blue > X1_Blue) and (Y0_Green >= value_Green < Y1_Green) => amarelamento moderado
```

Faz sentido?
