### ISSUE TITLE
Remover fundo e isolar o pellet

### ISSUE THREAD

**Issue by ocefpaf** [LaPoGeoMar/Proj_Pellets_Amarelamento#2]
@jojobozz fiz um exemplo aqui com algo que pode te ajudar: 

https://nbviewer.org/gist/ocefpaf/7a1a522ab7359aa2cab09f5624a3f42d

**Comment by jojobozz** [comment]
Oi @ocefpaf testei todas as imagens que tinhamos (246) e apenas 136 foram recortadas, aí fiz uma pr agora adicionando uma pasta com todas as fotos que deram erro, das que funcionaram não consegui nenhuma foto da classificação da dani para amarelamento moderado e amarelamento muito alto (alterei as fotos na pasta classe_zanetti tb, com as fotos padrão da dani que tinham recorte)

**Comment by ocefpaf** [comment]
Blz. Essa semana estou num encontro de trabalho mas olho isso semana que vem. Confesso que esperava um número mais baixo, mas se for um ajuste simples a gente consegue aumentar o número de fotos para remoção do fundo.

**Comment by ocefpaf** [comment]
@jojobozz [fiz esse script](https://gist.github.com/ocefpaf/dc6379de4fe13491ad7404c9bf043edd) para investigar image por image e com um "threshold" da area dá pra recuperar a maioria delas.

O "truque" é nessas linhas caso queira implementar direto no seu notebook:

```python
threshold = pellet.area * 0.01
maskr = morphology.remove_small_objects(mask, pellet.area - threshold)
```

Antes a gente removia tudo que fosse menor que a maior area, mas por problemas de precisão numérica, as vezes era removido a area maior tbm. Ao remove o que é menor que 90% da area maior conseguimos garantir que a area maior fica.

**Comment by ocefpaf** [comment]
@jojobozz acho que podemos fechar esse aqui. Se discordar abre ele novamente e a gente tentar tirar qualquer dúvida que tenha ficado.
